package com.lftechnology.java.training.srijan.basics;

import java.security.SecureRandom;
import java.util.Scanner;
import java.util.logging.Logger;
/**
 * Write a Guessing a number game application: 
 * application will generate a random no between 1 and 20. 
 * user guess the value by entering from the console
 * Check if the guess value matched with random number or not, 
 * if matched show the guessing value, random value and the no. of attempts.
 */
public class GuessingNumbers {
	private int numberOfAttempt;
	private static final Logger LOGGER = Logger.getLogger(GuessingNumbers.class.getName());
	
	public GuessingNumbers(){
		numberOfAttempt = 0;
	}
	
	public static void main(String[] args){
		Scanner input = null;
		SecureRandom randomNumber = new SecureRandom();
		GuessingNumbers guessNumber = new GuessingNumbers();
		int guessedNumber;
		input = new Scanner(System.in);
		int randomGeneratedNumber = 1 + randomNumber.nextInt(19);
		LOGGER.info("random Generated Number:" + randomGeneratedNumber);
		
		do{
			LOGGER.info("Guess a number between 1 and 20:");
			guessedNumber = input.nextInt();
			
			if(guessedNumber != randomGeneratedNumber){
				guessNumber.numberOfAttempt++;
			}
				
			
		}while(guessedNumber != randomGeneratedNumber);
		
		LOGGER.info("Number of Attempts = " + guessNumber.numberOfAttempt);
		LOGGER.info("Random number generated by computer:" + randomGeneratedNumber);
		LOGGER.info("Matched guessed Number:" + guessedNumber);
		input.close();
	}
}
